// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz_u4_K7UTbxJfzt_EimZ8XBBuacOEHF4',
    appId: '1:812318828001:web:43a55612428878b2899ea0',
    messagingSenderId: '812318828001',
    projectId: 'examen2-f9940',
    authDomain: 'examen2-f9940.firebaseapp.com',
    storageBucket: 'examen2-f9940.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxBvTWmJABoGSgI0dyw5nCX64AHs9fFI',
    appId: '1:812318828001:android:3a92ca1f277dee92899ea0',
    messagingSenderId: '812318828001',
    projectId: 'examen2-f9940',
    storageBucket: 'examen2-f9940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsKs50fDAclsMxN5SdhAyO-9kkEnnbG4E',
    appId: '1:812318828001:ios:726c7384c6b7bcd3899ea0',
    messagingSenderId: '812318828001',
    projectId: 'examen2-f9940',
    storageBucket: 'examen2-f9940.appspot.com',
    iosBundleId: 'com.example.examen2617111397',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsKs50fDAclsMxN5SdhAyO-9kkEnnbG4E',
    appId: '1:812318828001:ios:726c7384c6b7bcd3899ea0',
    messagingSenderId: '812318828001',
    projectId: 'examen2-f9940',
    storageBucket: 'examen2-f9940.appspot.com',
    iosBundleId: 'com.example.examen2617111397',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz_u4_K7UTbxJfzt_EimZ8XBBuacOEHF4',
    appId: '1:812318828001:web:407c0e7060a819da899ea0',
    messagingSenderId: '812318828001',
    projectId: 'examen2-f9940',
    authDomain: 'examen2-f9940.firebaseapp.com',
    storageBucket: 'examen2-f9940.appspot.com',
  );
}
